{
    "openapi": "3.0.0",
    "info": {
        "title": "Your API Title",
        "description": "Your API Description",
        "version": "1.0.0"
    },
    "security": [
        {
            "BearerAuth": []
        }
    ],
    "components": {
        "securitySchemes": {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
    },
    "consumes": [
        "multipart/form-data"
    ],
    "paths": {
        "/api/evaluations{id}": {
            "delete": {
                "summary": "delete",
                "description": "",
                "responses": {
                    "204": {
                        "description": "Deleted successfully",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": [
                    "Evaluation"
                ],
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "type": "string"
                    },
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ]
            },
            "put": {
                "summary": "update",
                "description": "",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": [
                    "Evaluation"
                ],
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "type": "string"
                    },
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/x-www-form-urlencoded": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "date": {
                                        "type": "string"
                                    },
                                    "valeur": {
                                        "type": "integer"
                                    },
                                    "etudiant_id": {
                                        "type": "integer"
                                    },
                                    "matiere_id": {
                                        "type": "integer"
                                    },
                                    "ue_id": {
                                        "type": "integer"
                                    },
                                    "note": {
                                        "type": "integer"
                                    },
                                    "updated_at": {
                                        "type": "string"
                                    },
                                    "created_at": {
                                        "type": "string"
                                    }
                                }
                            },
                            "example": {
                                "date": "2024-08-06 12:00:00",
                                "valeur": 45,
                                "etudiant_id": 1,
                                "matiere_id": 2,
                                "ue_id": 3,
                                "note": 15,
                                "updated_at": "2024-08-06T19:37:45.000000Z",
                                "created_at": "2024-08-06T19:37:45.000000Z"
                            }
                        }
                    }
                }
            }
        },
        "/api/evaluations": {
            "get": {
                "summary": "affichage",
                "description": "",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": [
                    "Evaluation"
                ],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ]
            },
            "post": {
                "summary": "ajout",
                "description": "",
                "responses": {
                    "201": {
                        "description": "Created successfully",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": [
                    "Evaluation"
                ],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "id": {
                                        "type": "integer"
                                    },
                                    "date": {
                                        "type": "string"
                                    },
                                    "valeur": {
                                        "type": "integer"
                                    },
                                    "etudiant_id": {
                                        "type": "integer"
                                    },
                                    "matiere_id": {
                                        "type": "integer"
                                    },
                                    "ue_id": {
                                        "type": "integer"
                                    },
                                    "note": {
                                        "type": "string"
                                    },
                                    "created_at": {
                                        "type": "string"
                                    },
                                    "updated_at": {
                                        "type": "string"
                                    }
                                }
                            },
                            "example": {
                                "id": 6,
                                "date": "2024-08-06 12:00:00",
                                "valeur": 45,
                                "etudiant_id": 1,
                                "matiere_id": 2,
                                "ue_id": 3,
                                "note": "15.00",
                                "created_at": "2024-08-06T19:37:45.000000Z",
                                "updated_at": "2024-08-06T19:37:45.000000Z"
                            }
                        }
                    }
                }
            }
        },
        "/api/etudiants{id}": {
            "delete": {
                "summary": "delete",
                "description": "",
                "responses": {
                    "204": {
                        "description": "Deleted successfully",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": [
                    "Etudiant"
                ],
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "type": "string"
                    },
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ]
            },
            "put": {
                "summary": "update",
                "description": "",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": [
                    "Etudiant"
                ],
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "type": "string"
                    },
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/x-www-form-urlencoded": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "nom": {
                                        "type": "string"
                                    },
                                    "prenom": {
                                        "type": "string"
                                    },
                                    "adresse": {
                                        "type": "string"
                                    },
                                    "matricule": {
                                        "type": "string"
                                    },
                                    "photo": {
                                        "type": "string"
                                    },
                                    "date_naissance": {
                                        "type": "string"
                                    },
                                    "email": {
                                        "type": "string"
                                    },
                                    "telephone": {
                                        "type": "integer"
                                    },
                                    "created_at": {
                                        "type": "string"
                                    },
                                    "updated_at": {
                                        "type": "string"
                                    },
                                    "deleted_at": {
                                        "type": "string",
                                        "format": "binary"
                                    }
                                }
                            },
                            "example": {
                                "nom": "fall",
                                "prenom": "John",
                                "adresse": "123 Main St",
                                "matricule": "A123456gggg",
                                "photo": "http://example.com/photo.jpg",
                                "date_naissance": "2000-01-01",
                                "email": "jkkdjdhhde@example.com",
                                "telephone": 92345678,
                                "created_at": "2024-08-06T17:00:07.000000Z",
                                "updated_at": "2024-08-07T10:53:17.000000Z",
                                "deleted_at": null
                            }
                        }
                    }
                }
            }
        },
        "/api/etudiants": {
            "post": {
                "summary": "ajout",
                "description": "",
                "responses": {
                    "201": {
                        "description": "Created successfully",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": [
                    "Etudiant"
                ],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "id": {
                                        "type": "integer"
                                    },
                                    "nom": {
                                        "type": "string"
                                    },
                                    "prenom": {
                                        "type": "string"
                                    },
                                    "adresse": {
                                        "type": "string"
                                    },
                                    "matricule": {
                                        "type": "string"
                                    },
                                    "photo": {
                                        "type": "string"
                                    },
                                    "date_naissance": {
                                        "type": "string"
                                    },
                                    "email": {
                                        "type": "string"
                                    },
                                    "telephone": {
                                        "type": "string"
                                    },
                                    "created_at": {
                                        "type": "string"
                                    },
                                    "updated_at": {
                                        "type": "string"
                                    },
                                    "deleted_at": {
                                        "type": "string",
                                        "format": "binary"
                                    }
                                }
                            },
                            "example": {
                                "id": 3,
                                "nom": "Doe",
                                "prenom": "John",
                                "adresse": "123 Main St",
                                "matricule": "A123456ff",
                                "photo": "http://example.com/photo.jpg",
                                "date_naissance": "2000-01-01",
                                "email": "john@example.com",
                                "telephone": "1234567790",
                                "created_at": "2024-08-06T17:00:07.000000Z",
                                "updated_at": "2024-08-06T17:00:07.000000Z",
                                "deleted_at": null
                            }
                        }
                    }
                }
            },
            "get": {
                "summary": "affichage",
                "description": "",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": [
                    "Etudiant"
                ],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ]
            }
        },
        "/api/matieres/{id}": {
            "delete": {
                "summary": "suppression",
                "description": "",
                "responses": {
                    "204": {
                        "description": "Deleted successfully",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": [
                    "Matiere"
                ],
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "type": "string"
                    },
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ]
            },
            "post": {
                "summary": "ajout",
                "description": "",
                "responses": {
                    "201": {
                        "description": "Created successfully",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": [
                    "Unité d'enseignement"
                ],
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "type": "string"
                    },
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "id": {
                                        "type": "integer"
                                    },
                                    "libelle": {
                                        "type": "string"
                                    },
                                    "date_debut": {
                                        "type": "string"
                                    },
                                    "date_fin": {
                                        "type": "string"
                                    },
                                    "ue_id": {
                                        "type": "integer"
                                    },
                                    "created_at": {
                                        "type": "string"
                                    },
                                    "updated_at": {
                                        "type": "string"
                                    }
                                }
                            },
                            "example": {
                                "id": 21,
                                "libelle": "suscipit",
                                "date_debut": "2024-06-25 06:54:52",
                                "date_fin": "2025-03-06 00:32:22",
                                "ue_id": 12,
                                "created_at": "2024-08-06T16:48:32.000000Z",
                                "updated_at": "2024-08-06T16:48:32.000000Z"
                            }
                        }
                    }
                }
            }
        },
        "/api/matieres": {
            "post": {
                "summary": "ajout",
                "description": "",
                "responses": {
                    "201": {
                        "description": "Created successfully",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": [
                    "Matiere"
                ],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "id": {
                                        "type": "integer"
                                    },
                                    "libelle": {
                                        "type": "string"
                                    },
                                    "date_debut": {
                                        "type": "string"
                                    },
                                    "date_fin": {
                                        "type": "string"
                                    },
                                    "ue_id": {
                                        "type": "integer"
                                    },
                                    "created_at": {
                                        "type": "string"
                                    },
                                    "updated_at": {
                                        "type": "string"
                                    }
                                }
                            },
                            "example": {
                                "id": 1,
                                "libelle": "suscipit",
                                "date_debut": "2024-06-25 06:54:52",
                                "date_fin": "2025-03-06 00:32:22",
                                "ue_id": 12,
                                "created_at": "2024-08-06T16:48:32.000000Z",
                                "updated_at": "2024-08-06T16:48:32.000000Z"
                            }
                        }
                    }
                }
            },
            "get": {
                "summary": "affichage",
                "description": "",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": [
                    "Matiere"
                ],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ]
            }
        },
        "/api/matieres{id}": {
            "put": {
                "summary": "update",
                "description": "",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": [
                    "Matiere"
                ],
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "type": "string"
                    },
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/x-www-form-urlencoded": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "libelle": {
                                        "type": "string"
                                    },
                                    "date_debut": {
                                        "type": "string"
                                    },
                                    "date_fin": {
                                        "type": "string"
                                    },
                                    "ue_id": {
                                        "type": "integer"
                                    },
                                    "created_at": {
                                        "type": "string"
                                    },
                                    "updated_at": {
                                        "type": "string"
                                    }
                                }
                            },
                            "example": {
                                "libelle": "suscipinnnnnnnnnnnt",
                                "date_debut": "2024-06-25 06:54:52",
                                "date_fin": "2025-03-06 00:32:22",
                                "ue_id": 12,
                                "created_at": "2024-08-06T16:48:32.000000Z",
                                "updated_at": "2024-08-06T16:48:32.000000Z"
                            }
                        }
                    }
                }
            }
        },
        "/api/ues/{id}": {
            "delete": {
                "summary": "delete",
                "description": "",
                "responses": {
                    "204": {
                        "description": "Deleted successfully",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": [
                    "Unité d'enseignement"
                ],
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "type": "string"
                    },
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ]
            },
            "put": {
                "summary": "update",
                "description": "",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": [
                    "Unité d'enseignement"
                ],
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "type": "string"
                    },
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/x-www-form-urlencoded": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "id": {
                                        "type": "integer"
                                    },
                                    "date_debut": {
                                        "type": "string"
                                    },
                                    "date_fin": {
                                        "type": "string"
                                    },
                                    "coef": {
                                        "type": "integer"
                                    },
                                    "libelle": {
                                        "type": "string"
                                    },
                                    "created_at": {
                                        "type": "string"
                                    },
                                    "updated_at": {
                                        "type": "string"
                                    }
                                }
                            },
                            "example": {
                                "id": 1,
                                "date_debut": "2024-06-13 15:32:59",
                                "date_fin": "2025-07-20 13:46:18",
                                "coef": 2,
                                "libelle": "aperiamjjjjjjjjjjj",
                                "created_at": "2024-08-06T16:48:32.000000Z",
                                "updated_at": "2024-08-06T16:48:32.000000Z"
                            }
                        }
                    }
                }
            }
        },
        "/api/ues": {
            "get": {
                "summary": "voir",
                "description": "",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": [
                    "Unité d'enseignement"
                ],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "id": {
                                        "type": "integer"
                                    },
                                    "date_debut": {
                                        "type": "string"
                                    },
                                    "date_fin": {
                                        "type": "string"
                                    },
                                    "coef": {
                                        "type": "integer"
                                    },
                                    "libelle": {
                                        "type": "string"
                                    },
                                    "created_at": {
                                        "type": "string"
                                    },
                                    "updated_at": {
                                        "type": "string"
                                    }
                                }
                            },
                            "example": {
                                "id": 1,
                                "date_debut": "2024-06-13 15:32:59",
                                "date_fin": "2025-07-20 13:46:18",
                                "coef": 2,
                                "libelle": "aperiam",
                                "created_at": "2024-08-06T16:48:32.000000Z",
                                "updated_at": "2024-08-06T16:48:32.000000Z"
                            }
                        }
                    }
                }
            }
        },
        "/api/login": {
            "post": {
                "summary": "login",
                "description": "",
                "responses": {
                    "201": {
                        "description": "Created successfully",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": [
                    "Auth"
                ],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    }
                                }
                            },
                            "example": {
                                "email": "fatishma121@gmail.com",
                                "password": "password"
                            }
                        }
                    }
                }
            }
        },
        "/api/logout": {
            "post": {
                "summary": "logout",
                "description": "",
                "responses": {
                    "201": {
                        "description": "Created successfully",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": [
                    "Auth"
                ],
                "parameters": [
                    {
                        "in": "path",
                        "name": "email",
                        "type": "string"
                    },
                    {
                        "in": "path",
                        "name": "password",
                        "type": "string"
                    },
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ]
            }
        },
        "/api/refresh": {
            "post": {
                "summary": "refresh",
                "description": "",
                "responses": {
                    "201": {
                        "description": "Created successfully",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": ""
                            }
                        }
                    }
                },
                "tags": [
                    "ApiPolarisEcoleEvaluation"
                ],
                "parameters": [
                    {
                        "in": "path",
                        "name": "",
                        "type": "string"
                    },
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    }
                                }
                            },
                            "example": {
                                "email": "fatishma121@gmail.com",
                                "password": "password"
                            }
                        }
                    }
                }
            }
        }
    }
}